name = "DABeams"
uuid = "efee0ea5-2685-47dd-aa2f-b675181c5e0b"
authors = ["Luiz Guilherme Pancini dos Santos"]
version = "1.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
